palstation/config/routes.rb
Rails.application.routes.draw do
  get 'stations/identity', to: 'stations#identity'
  get 'messages/outgoing', to: 'messages#outgoing'
  get 'messages/outbound/:id', to: 'messages#outbound'
  get 'messages/outbound_confirmed/:id', to: 'messages#outbound_confirmed'
  get 'messages/outbound_unconfirmed/:id', to: 'messages#outbound_unconfirmed'


  resources :stations
  resources :messages
  resources :waypoints
  resources :flightplans
  resources :payloads
  resources :weathers
  resources :pals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

palstation/app/models/pal.rb
class Pal < ApplicationRecord
  belongs_to :payload, optional: true
  belongs_to :flightplan, optional: true
end

palstation/app/controllers/pals_controller.rb
class PalsController < ApplicationController
  before_action :set_pal, only: [:show, :edit, :update, :destroy]

  # GET /pals
  # GET /pals.json
  def index
    @pals = Pal.all
  end

  # GET /pals/1
  # GET /pals/1.json
  def show
  end

  # GET /pals/new
  def new
    @pal = Pal.new
  end

  # GET /pals/1/edit
  def edit
  end

  # POST /pals
  # POST /pals.json
  def create
    @pal = Pal.new(pal_params)

    respond_to do |format|
      if @pal.save
        format.html { redirect_to @pal, notice: 'Pal was successfully created.' }
        format.json { render :show, status: :created, location: @pal }
      else
        format.html { render :new }
        format.json { render json: @pal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pals/1
  # PATCH/PUT /pals/1.json
  def update
    respond_to do |format|
      if @pal.update(pal_params)
        format.html { redirect_to @pal, notice: 'Pal was successfully updated.' }
        format.json { render :show, status: :ok, location: @pal }
      else
        format.html { render :edit }
        format.json { render json: @pal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pals/1
  # DELETE /pals/1.json
  def destroy
    @pal.destroy
    respond_to do |format|
      format.html { redirect_to pals_url, notice: 'Pal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pal
      @pal = Pal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pal_params
      params.require(:pal).permit(:status, :location, :lat, :long, :payload_id, :flightplan_id)
    end
end

palstation/app/helpers/pals_helper.rb
module PalsHelper
end

palstation/app/views/pals/_form.html.erb
<%= form_with(model: pal, local: true) do |form| %>
  <% if pal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pal.errors.count, "error") %> prohibited this pal from being saved:</h2>

      <ul>
      <% pal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat %>
  </div>

  <div class="field">
    <%= form.label :long %>
    <%= form.text_field :long %>
  </div>

  <div class="field">
    <%= form.label :payload_id %>
    <%= form.text_field :payload_id %>
  </div>

  <div class="field">
    <%= form.label :flightplan_id %>
    <%= form.text_field :flightplan_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

palstation/app/views/pals/edit.html.erb
<h1>Editing Pal</h1>

<%= render 'form', pal: @pal %>

<%= link_to 'Show', @pal %> |
<%= link_to 'Back', pals_path %>

palstation/app/views/pals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pals</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Location</th>
      <th>Lat</th>
      <th>Long</th>
      <th>Payload</th>
      <th>Flightplan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pals.each do |pal| %>
      <tr>
        <td><%= pal.status %></td>
        <td><%= pal.location %></td>
        <td><%= pal.lat %></td>
        <td><%= pal.long %></td>
        <td><%= pal.payload %></td>
        <td><%= pal.flightplan %></td>
        <td><%= link_to 'Show', pal %></td>
        <td><%= link_to 'Edit', edit_pal_path(pal) %></td>
        <td><%= link_to 'Destroy', pal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pal', new_pal_path %>

palstation/app/views/pals/new.html.erb
<h1>New Pal</h1>

<%= render 'form', pal: @pal %>

<%= link_to 'Back', pals_path %>

palstation/app/views/pals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @pal.status %>
</p>

<p>
  <strong>Location:</strong>
  <%= @pal.location %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @pal.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @pal.long %>
</p>

<p>
  <strong>Payload:</strong>
  <%= @pal.payload %>
</p>

<p>
  <strong>Flightplan:</strong>
  <%= @pal.flightplan %>
</p>

<%= link_to 'Edit', edit_pal_path(@pal) %> |
<%= link_to 'Back', pals_path %>