palstation/config/routes.rb
Rails.application.routes.draw do
  get 'stations/identity', to: 'stations#identity'
  get 'messages/outgoing', to: 'messages#outgoing'
  get 'messages/outbound/:id', to: 'messages#outbound'
  get 'messages/outbound_confirmed/:id', to: 'messages#outbound_confirmed'
  get 'messages/outbound_unconfirmed/:id', to: 'messages#outbound_unconfirmed'


  resources :stations
  resources :messages
  resources :waypoints
  resources :flightplans
  resources :payloads
  resources :weathers
  resources :pals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

palstation/app/models/payload.rb
class Payload < ApplicationRecord
  belongs_to :pal
end

palstation/app/controllers/payloads_controller.rb
class PayloadsController < ApplicationController
  before_action :set_payload, only: [:show, :edit, :update, :destroy]

  # GET /payloads
  # GET /payloads.json
  def index
    @payloads = Payload.all
  end

  # GET /payloads/1
  # GET /payloads/1.json
  def show
  end

  # GET /payloads/new
  def new
    @payload = Payload.new
  end

  # GET /payloads/1/edit
  def edit
  end

  # POST /payloads
  # POST /payloads.json
  def create
    @payload = Payload.new(payload_params)

    respond_to do |format|
      if @payload.save
        format.html { redirect_to @payload, notice: 'Payload was successfully created.' }
        format.json { render :show, status: :created, location: @payload }
      else
        format.html { render :new }
        format.json { render json: @payload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payloads/1
  # PATCH/PUT /payloads/1.json
  def update
    respond_to do |format|
      if @payload.update(payload_params)
        format.html { redirect_to @payload, notice: 'Payload was successfully updated.' }
        format.json { render :show, status: :ok, location: @payload }
      else
        format.html { render :edit }
        format.json { render json: @payload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payloads/1
  # DELETE /payloads/1.json
  def destroy
    @payload.destroy
    respond_to do |format|
      format.html { redirect_to payloads_url, notice: 'Payload was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payload
      @payload = Payload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payload_params
      params.require(:payload).permit(:created_at, :is_sent, :is_received, :pal_id)
    end
end

palstation/app/helpers/payloads_helper.rb
module PayloadsHelper
end

palstation/app/views/payloads/_form.html.erb
<%= form_with(model: payload, local: true) do |form| %>
  <% if payload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payload.errors.count, "error") %> prohibited this payload from being saved:</h2>

      <ul>
      <% payload.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :created_at %>
    <%= form.datetime_select :created_at %>
  </div>

  <div class="field">
    <%= form.label :is_sent %>
    <%= form.check_box :is_sent %>
  </div>

  <div class="field">
    <%= form.label :is_received %>
    <%= form.check_box :is_received %>
  </div>

  <div class="field">
    <%= form.label :pal_id %>
    <%= form.text_field :pal_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

palstation/app/views/payloads/edit.html.erb
<h1>Editing Payload</h1>

<%= render 'form', payload: @payload %>

<%= link_to 'Show', @payload %> |
<%= link_to 'Back', payloads_path %>

palstation/app/views/payloads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payloads</h1>

<table>
  <thead>
    <tr>
      <th>Created at</th>
      <th>Is sent</th>
      <th>Is received</th>
      <th>Pal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payloads.each do |payload| %>
      <tr>
        <td><%= payload.created_at %></td>
        <td><%= payload.is_sent %></td>
        <td><%= payload.is_received %></td>
        <td><%= payload.pal %></td>
        <td><%= link_to 'Show', payload %></td>
        <td><%= link_to 'Edit', edit_payload_path(payload) %></td>
        <td><%= link_to 'Destroy', payload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payload', new_payload_path %>

palstation/app/views/payloads/new.html.erb
<h1>New Payload</h1>

<%= render 'form', payload: @payload %>

<%= link_to 'Back', payloads_path %>

palstation/app/views/payloads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Created at:</strong>
  <%= @payload.created_at %>
</p>

<p>
  <strong>Is sent:</strong>
  <%= @payload.is_sent %>
</p>

<p>
  <strong>Is received:</strong>
  <%= @payload.is_received %>
</p>

<p>
  <strong>Pal:</strong>
  <%= @payload.pal %>
</p>

<%= link_to 'Edit', edit_payload_path(@payload) %> |
<%= link_to 'Back', payloads_path %>