palstation/config/routes.rb
Rails.application.routes.draw do
  get 'stations/identity', to: 'stations#identity'
  get 'messages/outgoing', to: 'messages#outgoing'
  get 'messages/outbound/:id', to: 'messages#outbound'
  get 'messages/outbound_confirmed/:id', to: 'messages#outbound_confirmed'
  get 'messages/outbound_unconfirmed/:id', to: 'messages#outbound_unconfirmed'


  resources :stations
  resources :messages
  resources :waypoints
  resources :flightplans
  resources :payloads
  resources :weathers
  resources :pals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

palstation/app/models/waypoint.rb
class Waypoint < ApplicationRecord
  belongs_to :flightplan
end

palstation/app/controllers/waypoints_controller.rb
class WaypointsController < ApplicationController
  before_action :set_waypoint, only: [:show, :edit, :update, :destroy]

  # GET /waypoints
  # GET /waypoints.json
  def index
    @waypoints = Waypoint.all
  end

  # GET /waypoints/1
  # GET /waypoints/1.json
  def show
  end

  # GET /waypoints/new
  def new
    @waypoint = Waypoint.new
  end

  # GET /waypoints/1/edit
  def edit
  end

  # POST /waypoints
  # POST /waypoints.json
  def create
    @waypoint = Waypoint.new(waypoint_params)

    respond_to do |format|
      if @waypoint.save
        format.html { redirect_to @waypoint, notice: 'Waypoint was successfully created.' }
        format.json { render :show, status: :created, location: @waypoint }
      else
        format.html { render :new }
        format.json { render json: @waypoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waypoints/1
  # PATCH/PUT /waypoints/1.json
  def update
    respond_to do |format|
      if @waypoint.update(waypoint_params)
        format.html { redirect_to @waypoint, notice: 'Waypoint was successfully updated.' }
        format.json { render :show, status: :ok, location: @waypoint }
      else
        format.html { render :edit }
        format.json { render json: @waypoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waypoints/1
  # DELETE /waypoints/1.json
  def destroy
    @waypoint.destroy
    respond_to do |format|
      format.html { redirect_to waypoints_url, notice: 'Waypoint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_waypoint
      @waypoint = Waypoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def waypoint_params
      params.require(:waypoint).permit(:lat, :long, :step, :flightplan_id)
    end
end

palstation/app/helpers/waypoints_helper.rb
module WaypointsHelper
end

palstation/app/views/waypoints/_form.html.erb
<%= form_with(model: waypoint, local: true) do |form| %>
  <% if waypoint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(waypoint.errors.count, "error") %> prohibited this waypoint from being saved:</h2>

      <ul>
      <% waypoint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat %>
  </div>

  <div class="field">
    <%= form.label :long %>
    <%= form.text_field :long %>
  </div>

  <div class="field">
    <%= form.label :step %>
    <%= form.number_field :step %>
  </div>

  <div class="field">
    <%= form.label :flightplan_id %>
    <%= form.text_field :flightplan_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

palstation/app/views/waypoints/edit.html.erb
<h1>Editing Waypoint</h1>

<%= render 'form', waypoint: @waypoint %>

<%= link_to 'Show', @waypoint %> |
<%= link_to 'Back', waypoints_path %>

palstation/app/views/waypoints/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Waypoints</h1>

<table>
  <thead>
    <tr>
      <th>Lat</th>
      <th>Long</th>
      <th>Step</th>
      <th>Flightplan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @waypoints.each do |waypoint| %>
      <tr>
        <td><%= waypoint.lat %></td>
        <td><%= waypoint.long %></td>
        <td><%= waypoint.step %></td>
        <td><%= waypoint.flightplan %></td>
        <td><%= link_to 'Show', waypoint %></td>
        <td><%= link_to 'Edit', edit_waypoint_path(waypoint) %></td>
        <td><%= link_to 'Destroy', waypoint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Waypoint', new_waypoint_path %>

palstation/app/views/waypoints/new.html.erb
<h1>New Waypoint</h1>

<%= render 'form', waypoint: @waypoint %>

<%= link_to 'Back', waypoints_path %>

palstation/app/views/waypoints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lat:</strong>
  <%= @waypoint.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @waypoint.long %>
</p>

<p>
  <strong>Step:</strong>
  <%= @waypoint.step %>
</p>

<p>
  <strong>Flightplan:</strong>
  <%= @waypoint.flightplan %>
</p>

<%= link_to 'Edit', edit_waypoint_path(@waypoint) %> |
<%= link_to 'Back', waypoints_path %>