palstation/config/routes.rb
Rails.application.routes.draw do
  get 'stations/identity', to: 'stations#identity'
  get 'messages/outgoing', to: 'messages#outgoing'
  get 'messages/outbound/:id', to: 'messages#outbound'
  get 'messages/outbound_confirmed/:id', to: 'messages#outbound_confirmed'
  get 'messages/outbound_unconfirmed/:id', to: 'messages#outbound_unconfirmed'


  resources :stations
  resources :messages
  resources :waypoints
  resources :flightplans
  resources :payloads
  resources :weathers
  resources :pals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

palstation/app/models/weather.rb
class Weather < ApplicationRecord
  belongs_to :station
end

palstation/app/controllers/weathers_controller.rb
class WeathersController < ApplicationController
  before_action :set_weather, only: [:show, :edit, :update, :destroy]

  # GET /weathers
  # GET /weathers.json
  def index
    @weathers = Weather.all
  end

  # GET /weathers/1
  # GET /weathers/1.json
  def show
  end

  # GET /weathers/new
  def new
    @weather = Weather.new
  end

  # GET /weathers/1/edit
  def edit
  end

  # POST /weathers
  # POST /weathers.json
  def create
    @weather = Weather.new(weather_params)

    respond_to do |format|
      if @weather.save
        format.html { redirect_to @weather, notice: 'Weather was successfully created.' }
        format.json { render :show, status: :created, location: @weather }
      else
        format.html { render :new }
        format.json { render json: @weather.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weathers/1
  # PATCH/PUT /weathers/1.json
  def update
    respond_to do |format|
      if @weather.update(weather_params)
        format.html { redirect_to @weather, notice: 'Weather was successfully updated.' }
        format.json { render :show, status: :ok, location: @weather }
      else
        format.html { render :edit }
        format.json { render json: @weather.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weathers/1
  # DELETE /weathers/1.json
  def destroy
    @weather.destroy
    respond_to do |format|
      format.html { redirect_to weathers_url, notice: 'Weather was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weather
      @weather = Weather.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weather_params
      params.require(:weather).permit(:station_id, :score, :description, :updated_at)
    end
end

palstation/app/helpers/weathers_helper.rb
module WeathersHelper
end

palstation/app/views/weathers/_form.html.erb
<%= form_with(model: weather, local: true) do |form| %>
  <% if weather.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(weather.errors.count, "error") %> prohibited this weather from being saved:</h2>

      <ul>
      <% weather.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :station_id %>
    <%= form.text_field :station_id %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.text_field :score %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :updated_at %>
    <%= form.datetime_select :updated_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

palstation/app/views/weathers/edit.html.erb
<h1>Editing Weather</h1>

<%= render 'form', weather: @weather %>

<%= link_to 'Show', @weather %> |
<%= link_to 'Back', weathers_path %>

palstation/app/views/weathers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Weathers</h1>

<table>
  <thead>
    <tr>
      <th>Station</th>
      <th>Score</th>
      <th>Description</th>
      <th>Updated at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weathers.each do |weather| %>
      <tr>
        <td><%= weather.station %></td>
        <td><%= weather.score %></td>
        <td><%= weather.description %></td>
        <td><%= weather.updated_at %></td>
        <td><%= link_to 'Show', weather %></td>
        <td><%= link_to 'Edit', edit_weather_path(weather) %></td>
        <td><%= link_to 'Destroy', weather, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weather', new_weather_path %>

palstation/app/views/weathers/new.html.erb
<h1>New Weather</h1>

<%= render 'form', weather: @weather %>

<%= link_to 'Back', weathers_path %>

palstation/app/views/weathers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Station:</strong>
  <%= @weather.station %>
</p>

<p>
  <strong>Score:</strong>
  <%= @weather.score %>
</p>

<p>
  <strong>Description:</strong>
  <%= @weather.description %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @weather.updated_at %>
</p>

<%= link_to 'Edit', edit_weather_path(@weather) %> |
<%= link_to 'Back', weathers_path %>